#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# The depths you created files for
DEPTHS=(5 20 50 100)
PTAU="powersOfTau28_hez_final_15.ptau"

echo "========================================================="
echo " Starting ZKP Benchmark Build Process"
echo "========================================================="

# 1. Download the Power of Tau file if it doesn't exist using cURL
if [ ! -f "$PTAU" ]; then
    echo "Downloading Phase 1 Trusted Setup ($PTAU)..."
    echo "This supports up to 32,768 constraints (perfect for depth 100)."
    # Replaced wget with curl.
    # -O saves it with the remote filename
    # -L follows redirects if any
    curl -O -L "https://storage.googleapis.com/zkevm/ptau/powersOfTau28_hez_final_15.ptau"
else
    echo "Found existing $PTAU file."
fi

# 2. Create the output directory expected by your JS script
mkdir -p circuit_js

# 3. Loop through each depth and compile
for depth in "${DEPTHS[@]}"; do
    FILENAME="merkle_${depth}.circom"

    echo ""
    echo ">>> Compiling $FILENAME..."

    # Check if the file actually exists to prevent errors
    if [ ! -f "$FILENAME" ]; then
        echo "Error: $FILENAME not found! Skipping..."
        continue
    fi

    # Compile using your specific executable
    ./circom.exe "$FILENAME" --r1cs --wasm --sym -o ./

    # Move the generated WASM file to the circuit_js directory
    echo "Moving WASM file..."
    mv "merkle_${depth}_js/merkle_${depth}.wasm" circuit_js/

    # Clean up the leftover JS folder generated by Circom
    rm -rf "merkle_${depth}_js"

    # Generate the Groth16 ZKEY (Prover Key)
    echo "Generating ZKEY for depth $depth..."
    npx snarkjs groth16 setup "merkle_${depth}.r1cs" "$PTAU" "merkle_${depth}.zkey"

    echo "Finished depth $depth!"
done

echo ""
echo "========================================================="
echo " Build Complete! All artifacts are ready."
echo " You can now run: node scripts/bench_complexity.js"
echo "========================================================="